--- 
blank_issues_enabled: true
contact_links: 
  - 
    about: "If you can't figure something out, ask us!"
    name: "Question"
    url: "https://github.com/Joe91/fun-bots/discussions/categories/q-a"
