name: Documentation Enhancement
description: Is something wrong on the wiki? Saw a typo somewhere? Missing something? Create a documentation issue and we'll handle it from there.
labels: [documentation]
assignees:
  - Firjens
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a documentation-related issue. We'd highly appreciate if for large documentation changes you'd create a [pull request](https://github.com/Joe91/fun-bots/pulls) as it can save us a lot of time.
  - type: input
    id: location
    attributes:
      label: Location
      description: Which page(s) are affected and should be modified?
      placeholder: ex. github.com/Joe91/fun-bots/wiki/Permissions
    validations:
      required: false
  - type: textarea
    id: what-wrong
    attributes:
      label: What's wrong?
      description: What's the issue and should be modified?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: I have checked the following...
      description: Before submitting this documentation enhancement issue, checkout the contributing guidelines and our code of conduct.
      options:
        - label: I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
          required: true