name: Enhancement Request
description: I'd like to see a change to an existing feature.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Great [TBA].
  - type: textarea
    id: what-happened
    attributes:
      label: Requested feature
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Requested feature
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
