name: Feature Request
description: I'd like to see a new feature added to fun-bots.
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        We always appreciate new ideas for fun-bots, but before posting a new feature idea, maybe we already have it planned? Check the [projects page](https://github.com/Joe91/fun-bots/projects) to see what has been already planned, or it may already planned.
  - type: textarea
    id: feature
    attributes:
      label: Requested feature
      description: What would you like to see added? In which situations would this be helpful?
    validations:
      required: true
