name: Traces Bug Report
description: Is there something wrong with the default traces? 
labels: [bug, traces]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What happened what should not have happened? Please also tell us how we can reproduce it. The more information the better.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: What was expected?
      description: What did you expect to happen?
      placeholder: What you should see instead.
    validations:
      required: true
